#!/usr/bin/env bash

load_media_background(){
    "$HOME/src/background-fm/background-media-chooser.sh"
    touch "$HOME/.cache/background-media/.herbstluft"
    while [[ -f "$HOME/.cache/background-media/.herbstluft" ]]; do
        inotifywait -e close_write -e delete "$HOME/.cache/background-media/.herbstluft" "$HOME/.cache/background-media/"
        echo updating background
        if [[ $(herbstclient get_attr tags.focus.name) == "4." ]]; then
            "$HOME/src/background-fm/background-media-chooser.sh"
        fi
    done
}

set_background(){
    feh --bg-tile $1
}
load_standard_background(){
    set_background "$HOME/linux-background.png"
    if [[ -f "$HOME/.cache/background-media/.herbstluft" ]]; then
        rm "$HOME/.cache/background-media/.herbstluft"
    fi
}
declare -A WALLPAPER
WALLPAPER=(
    #Default wallpaper
    [0]=load_standard_background
    [4.]=load_media_background
)



${WALLPAPER[0]}
# background on tags (taken from https://gist.github.com/wdkrnls/b444ef77d450b7b0c24c934bba861760
herbstclient --idle '(tag_changed|quit_panel|reload)' \
    | while read line; do
    ARGS=($line)
    HOOK=${ARGS[0]}
    TAG=${ARGS[1]}
    case $HOOK in
        reload)
            exit 1
            ;;
        quit_panel)
            exit 1
            ;;
        tag_changed)
            if [ -z "${WALLPAPER[$TAG]}" ]; then
                # No wallpaper for tag
                WALL=${WALLPAPER[0]}
            else
                # Wallpaper for tag
                WALL=${WALLPAPER[$TAG]}
            fi
            $WALL &
            ;; 
        *) ;;
    esac
done
